INSERT INTO USER (ID, VERSION, BIRTHDAY, EMAIL, NAME, PASSW, ROLE, USERNAME) VALUES (1, 1, '1995-04-12', 'alma@alma.com', 'Full Name', 'password', 'ADMIN', 'User');
INSERT INTO REQUEST (ID, VERSION, DIRECTOR, TITLE, YEAR, USER_ID) VALUES (1, 1, 'Dummy Director', 'Please make available this movie', 1993, 1);
INSERT INTO GENRE (ID,VERSION,NAME) VALUES (1,1,'HORROR');
INSERT INTO MOVIE (ID,VERSION,DESCRIPTION,DIRECTOR,GENRE_ID,TITLE,YEAR) VALUES (1,1,'This film is... zzz','Quite Good Director',1,'First movie in the db',1989);
INSERT INTO ACTOR (ID, VERSION, BIRTHDAY, NAME) VALUES (1, 1, '1954-12-12', 'John Actor');
INSERT INTO ACTOR_MOVIES (ACTORS_ID, MOVIES_ID) VALUES (1,1);
INSERT INTO LOAN (ID, VERSION, LOAN_END, LOAN_START, MOVIE_ID, USER_ID) VALUES (1,1,'2017-11-14 23:33:22','2017-11-10 01:58:22',1,1);
INSERT INTO RATE (ID, VERSION, OPINION, POINT_VALUE, RATE_ADDED, MOVIE_ID, USER_ID) VALUES (1,1,'This film is quite enough.',5,'2017-11-12 01:58:22',1,1);


-- INSERT INTO ACTOR (ID, VERSION, BIRTHDAY, NAME) VALUES (, , , '');
-- INSERT INTO ACTOR_MOVIES (ACTORS_ID, MOVIES_ID) VALUES (,);
-- INSERT INTO GENRE (ID, VERSION, NAME) VALUES (,,'');
-- INSERT INTO LOAN (ID, VERSION, LOAN_END, LOAN_START, MOVIE_ID, USER_ID) VALUES (,,'','',,);
-- INSERT INTO MOVIE (ID, VERSION, DESCRIPTION, DIRECTOR, TITLE, YEAR, GENRE_ID) VALUES (,,'','','',,);
-- INSERT INTO RATE (ID, VERSION, OPINION, POINT_VALUE, RATE_ADDED, MOVIE_ID, USER_ID) VALUES ();
-- INSERT INTO REQUEST (ID, VERSION, DIRECTOR, TITLE, YEAR, USER_ID) VALUES ();
-- INSERT INTO USER (ID, VERSION, BIRTHDAY, EMAIL, NAME, PASSW, ROLE, USERNAME) VALUES (,,,'','','','','');